#include "keymap_common.h"

const uint8_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[0] = KEYMAP( /* Base */
  TAB, Q, W, E, R, T, Y, U, I, O, P, MINS, 
  LCTL, A, S, D, F, G, H, J, K, L, SCLN, QUOTE, 
  LSFT, Z, X, C, V, FN6, FN5, M, COMM, DOT, SLSH, LSFT, 
  ESC, LCTL, LALT, LGUI, FN2, FN4, FN3, RGUI, RALT, FN5, TRNS),
[1] = KEYMAP( /* numbers*/
  GRV, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, TRNS, 
  TRNS, TRNS, TRNS, TRNS, TRNS, MS_L, MS_D, EQL, LBRC, RBRC, BSLS, TRNS, 
  TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, EQL, LBRC, RBRC, BSLS, 
  TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, MS_BTN1, MS_BTN2, TRNS, TRNS, TRNS),
[2] = KEYMAP( /* Shifted Numbers */
  FN10, FN11, FN12, FN13, FN14, FN15, FN16, FN17, FN18, FN19, FN20, FN21, 
  TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, FN22, FN24, FN25, FN26, 
  TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, 
  TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS),
[3] = KEYMAP( /* Media + Macros, keys on left side of board*/
  POWER, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, 
  TRNS, MPRV, MPLY, MNXT, VOLD, VOLU, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, 
  TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, 
  TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS), 
[4] = KEYMAP( /* Mouse + Arrow, keys on right side of board*/
  TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, 
  TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, MS_L, MS_D, MS_U, MS_R, TRNS, TRNS, 
  TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, LEFT, DOWN, UP, RIGHT, TRNS, TRNS, 
  TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, MS_BTN1, MS_BTN2, TRNS, TRNS, TRNS),
};
const uint16_t PROGMEM fn_actions[] = {
    [2] = ACTION_LAYER_TAP_KEY(1, KC_BSPC), // Numbers
    [3] = ACTION_LAYER_TAP_KEY(2, KC_ENT), // Shifted Numbers
    [4] = ACTION_MODS_TAP_KEY(MOD_LSFT, KC_SPC),
    [5] = ACTION_LAYER_TAP_KEY(3, KC_N), // Media Keys
    [6] = ACTION_LAYER_TAP_KEY(4, KC_B), // Mouse and Arrows

    [10] = ACTION_MODS_KEY(MOD_LSFT, KC_GRV),
    [11] = ACTION_MODS_KEY(MOD_LSFT, KC_1),
    [12] = ACTION_MODS_KEY(MOD_LSFT, KC_2),
    [13] = ACTION_MODS_KEY(MOD_LSFT, KC_3),
    [14] = ACTION_MODS_KEY(MOD_LSFT, KC_4),
    [15] = ACTION_MODS_KEY(MOD_LSFT, KC_5),
    [16] = ACTION_MODS_KEY(MOD_LSFT, KC_6),
    [17] = ACTION_MODS_KEY(MOD_LSFT, KC_7),
    [18] = ACTION_MODS_KEY(MOD_LSFT, KC_8),
    [19] = ACTION_MODS_KEY(MOD_LSFT, KC_9),
    [20] = ACTION_MODS_KEY(MOD_LSFT, KC_0),
    [21] = ACTION_MODS_KEY(MOD_LSFT, KC_MINS),
    [22] = ACTION_MODS_KEY(MOD_LSFT, KC_EQL),
    [23] = ACTION_MODS_KEY(MOD_LSFT, KC_GRV),
    [24] = ACTION_MODS_KEY(MOD_LSFT, KC_LBRC),
    [25] = ACTION_MODS_KEY(MOD_LSFT, KC_RBRC),
    [26] = ACTION_MODS_KEY(MOD_LSFT, KC_BSLS),
};
